[project]
name = "pennylane-support"
version = "0.1.0"
description = ""
authors = [
    {name = "Anton Moiseev"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard] (>=0.121.3,<0.122.0)"
]

[tool.poetry]
packages = [{include = "pennylane_support", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
